Method: GET
URL:    http://localhost:5000/api/timetable/today
Header: Authorization: Bearer <eyJhbGciOiJFUzI1NiIsImtpZCI6IjI3ZTM2Y2IzLTUzYTEtNDY3Ni04YzFmLWU5NWEwY2I3ZGJiMyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL29xaGpneGNwemdvcnFreHF5ZXZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyODM1NDU3MS05YTlmLTQzYmMtOGIxZi1lNzQ0ODIwZTQzNjkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc4NjAwMzY3LCJpYXQiOjE3Nzg1OTY3NjcsImVtYWlsIjoidmVua3lAY29sbGVnZS5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc3ODU5Njc2N31dLCJzZXNzaW9uX2lkIjoiYzQ4MTk1YTEtM2VhYi00NDAxLTgzOGEtMTE5MDMxODk5NmIyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.eD-XbuxceTA_6enZaXCGhyWuPvkdJ5yJLhOf92XI03ro2LzUQI9IaeopJhE9Bmc4qtYOokWmOcaBkvZOELSJcw>